import type { Product } from '@/types';

export const products: Product[] = [
  {
    id: 1,
    name: 'Cheeseburger Deluxe',
    description: 'A juicy beef patty with melted cheddar, lettuce, tomato, and our special sauce on a toasted bun.',
    price: 8.99,
    category: 'Burgers',
    image: '/burger.jpg',
    rating: 4.5,
    bestseller: true,
  },
  {
    id: 2,
    name: 'Classic Pepperoni',
    description: 'A crowd-pleaser with rich tomato sauce, mozzarella, and a generous layer of pepperoni.',
    price: 12.99,
    category: 'Pizza',
    image: 'https://placehold.co/600x400.png',
    rating: 4.8,
    bestseller: true,
  },
  {
    id: 3,
    name: 'Crispy Golden Fries',
    description: 'Perfectly golden and crispy french fries, lightly salted and served hot.',
    price: 3.49,
    category: 'Fries',
    image: 'https://placehold.co/600x400.png',
    rating: 4.2,
  },
  {
    id: 4,
    name: 'Ice-Cold Cola',
    description: 'A refreshing can of classic cola to quench your thirst and complete your meal.',
    price: 1.99,
    category: 'Beverages',
    image: 'https://placehold.co/600x400.png',
    rating: 4.6,
  },
  {
    id: 5,
    name: 'Veggie Supreme Pizza',
    description: 'Loaded with fresh bell peppers, onions, olives, and mushrooms on our classic tomato base.',
    price: 14.99,
    category: 'Pizza',
    image: 'https://placehold.co/600x400.png',
    rating: 4.4,
  },
  {
    id: 6,
    name: 'Spicy Chicken Burger',
    description: 'A fiery, crispy chicken fillet with spicy mayo, jalapeños, and fresh lettuce.',
    price: 9.99,
    category: 'Burgers',
    image: 'https://placehold.co/600x400.png',
    rating: 4.7,
    bestseller: true,
  },
  {
    id: 7,
    name: 'Crunchy Onion Rings',
    description: 'Thick-cut onion rings battered and fried to a perfect golden brown. Served with dipping sauce.',
    price: 4.99,
    category: 'Fries',
    image: 'https://placehold.co/600x400.png',
    rating: 4.3,
  },
  {
    id: 8,
    name: 'Fresh Lemonade',
    description: 'A zesty and refreshing homemade lemonade, perfect for a sunny day.',
    price: 2.49,
    category: 'Beverages',
    image: 'https://placehold.co/600x400.png',
    rating: 4.5,
  },
  {
    id: 9,
    name: 'Family Feast Combo',
    description: 'The perfect meal for four: 2 large pizzas, a family-size fries, and a 2-liter soda.',
    price: 29.99,
    category: 'Combos',
    image: 'https://placehold.co/600x400.png',
    rating: 4.9,
  },
  {
    id: 10,
    name: 'Margherita Pizza',
    description: 'Simple yet delicious, with fresh basil, mozzarella, and our signature tomato sauce.',
    price: 10.99,
    category: 'Pizza',
    image: 'https://placehold.co/600x400.png',
    rating: 4.1,
  },
  {
    id: 11,
    name: 'Bacon BBQ Burger',
    description: 'Smoky BBQ sauce, crispy bacon, and melted cheddar top our classic beef patty.',
    price: 10.49,
    category: 'Burgers',
    image: 'https://placehold.co/600x400.png',
    rating: 4.6,
  },
  {
    id: 12,
    name: 'Burger & Fries Combo',
    description: 'A classic Cheeseburger Deluxe paired with a medium portion of our crispy golden fries.',
    price: 11.49,
    category: 'Combos',
    image: 'https://placehold.co/600x400.png',
    rating: 4.7,
  },
  {
    id: 13,
    name: 'Mushroom Swiss Burger',
    description: 'Sautéed mushrooms and melted Swiss cheese on a juicy beef patty. A savory delight.',
    price: 11.99,
    category: 'Burgers',
    image: 'https://placehold.co/600x400.png',
    rating: 4.8,
  },
  {
    id: 14,
    name: 'Double Decker Burger',
    description: 'Two beef patties, special sauce, lettuce, cheese, pickles, onions on a sesame seed bun.',
    price: 13.99,
    category: 'Burgers',
    image: 'https://placehold.co/600x400.png',
    rating: 4.9,
  },
  {
    id: 15,
    name: 'Vegan Black Bean Burger',
    description: 'A hearty and delicious black bean patty topped with avocado and pico de gallo.',
    price: 10.99,
    category: 'Burgers',
    image: 'https://placehold.co/600x400.png',
    rating: 4.4,
  },
  {
    id: 16,
    name: 'Hawaiian Pizza',
    description: 'A tropical delight with sweet pineapple chunks and savory ham.',
    price: 13.99,
    category: 'Pizza',
    image: 'https://placehold.co/600x400.png',
    rating: 4.0,
  },
  {
    id: 17,
    name: 'BBQ Chicken Pizza',
    description: 'Tangy BBQ sauce, grilled chicken, red onions, and cilantro.',
    price: 15.49,
    category: 'Pizza',
    image: 'https://placehold.co/600x400.png',
    rating: 4.7,
  },
  {
    id: 18,
    name: 'Meat Lover\'s Pizza',
    description: 'Packed with pepperoni, sausage, ham, bacon, and beef.',
    price: 16.99,
    category: 'Pizza',
    image: 'https://placehold.co/600x400.png',
    rating: 4.8,
  },
  {
    id: 19,
    name: 'Curly Fries',
    description: 'Fun, spring-shaped fries with a seasoned coating for extra flavor.',
    price: 4.49,
    category: 'Fries',
    image: 'https://placehold.co/600x400.png',
    rating: 4.5,
  },
  {
    id: 20,
    name: 'Sweet Potato Fries',
    description: 'A slightly sweet and healthier alternative, served with a side of chipotle aioli.',
    price: 4.99,
    category: 'Fries',
    image: 'https://placehold.co/600x400.png',
    rating: 4.6,
  },
  {
    id: 21,
    name: 'Diet Cola',
    description: 'The same great cola taste with zero calories.',
    price: 1.99,
    category: 'Beverages',
    image: 'https://placehold.co/600x400.png',
    rating: 4.1,
  },
  {
    id: 22,
    name: 'Chocolate Milkshake',
    description: 'Thick, creamy, and rich chocolate milkshake made with real ice cream.',
    price: 4.99,
    category: 'Beverages',
    image: 'https://placehold.co/600x400.png',
    rating: 4.9,
  },
  {
    id: 23,
    name: 'Pizza & Wings Combo',
    description: 'A large pepperoni pizza with a dozen of our famous spicy chicken wings.',
    price: 24.99,
    category: 'Combos',
    image: 'https://placehold.co/600x400.png',
    rating: 4.7,
  },
  {
    id: 24,
    name: 'Double Burger Combo',
    description: 'Two Double Decker Burgers, two large fries, and two milkshakes.',
    price: 35.99,
    category: 'Combos',
    image: 'https://placehold.co/600x400.png',
    rating: 4.8,
  },
  {
    id: 25,
    name: 'Teriyaki Pineapple Burger',
    description: 'A juicy beef patty glazed with teriyaki sauce, topped with a grilled pineapple slice.',
    price: 11.49,
    category: 'Burgers',
    image: 'https://placehold.co/600x400.png',
    rating: 4.5,
  },
  {
    id: 26,
    name: 'Blue Cheese Burger',
    description: 'For the bold! A beef patty topped with tangy blue cheese crumbles and caramelized onions.',
    price: 12.49,
    category: 'Burgers',
    image: 'https://placehold.co/600x400.png',
    rating: 4.3,
  },
  {
    id: 27,
    name: 'Avocado Ranch Burger',
    description: 'Creamy avocado and zesty ranch dressing meet on top of our signature burger.',
    price: 12.49,
    category: 'Burgers',
    image: 'https://placehold.co/600x400.png',
    rating: 4.6,
  },
  {
    id: 28,
    name: 'Fish Fillet Burger',
    description: 'A crispy breaded fish fillet on a soft bun with tartar sauce and lettuce.',
    price: 9.49,
    category: 'Burgers',
    image: 'https://placehold.co/600x400.png',
    rating: 4.2,
  },
  {
    id: 29,
    name: 'Four Cheese Pizza',
    description: 'A cheese lover\'s dream: mozzarella, cheddar, provolone, and parmesan.',
    price: 14.99,
    category: 'Pizza',
    image: 'https://placehold.co/600x400.png',
    rating: 4.9,
  },
  {
    id: 30,
    name: 'Buffalo Chicken Pizza',
    description: 'Spicy buffalo sauce, tender chicken, and a drizzle of ranch dressing.',
    price: 15.99,
    category: 'Pizza',
    image: 'https://placehold.co/600x400.png',
    rating: 4.6,
  },
  {
    id: 31,
    name: 'Pesto Veggie Pizza',
    description: 'A vibrant pesto base with sun-dried tomatoes, spinach, and artichoke hearts.',
    price: 15.49,
    category: 'Pizza',
    image: 'https://placehold.co/600x400.png',
    rating: 4.5,
  },
  {
    id: 32,
    name: 'Supreme Pizza',
    description: 'The works! Pepperoni, sausage, peppers, onions, mushrooms, and olives.',
    price: 17.99,
    category: 'Pizza',
    image: 'https://placehold.co/600x400.png',
    rating: 4.8,
  },
  {
    id: 33,
    name: 'Cheese Fries',
    description: 'Our crispy golden fries smothered in warm, melted cheddar cheese sauce.',
    price: 4.99,
    category: 'Fries',
    image: 'https://placehold.co/600x400.png',
    rating: 4.4,
  },
  {
    id: 34,
    name: 'Bacon Cheese Fries',
    description: 'Cheese fries topped with crispy, savory bacon bits. Pure indulgence.',
    price: 5.99,
    category: 'Fries',
    image: 'https://placehold.co/600x400.png',
    rating: 4.7,
  },
  {
    id: 35,
    name: 'Garlic Parmesan Fries',
    description: 'Tossed in garlic butter and sprinkled with grated parmesan cheese and parsley.',
    price: 5.49,
    category: 'Fries',
    image: 'https://placehold.co/600x400.png',
    rating: 4.8,
  },
  {
    id: 36,
    name: 'Chili Cheese Fries',
    description: 'A hearty portion of fries topped with beef chili and melted cheese.',
    price: 6.99,
    category: 'Fries',
    image: 'https://placehold.co/600x400.png',
    rating: 4.6,
  },
  {
    id: 37,
    name: 'Waffle Fries',
    description: 'Crispy lattice-cut potatoes, perfect for dipping.',
    price: 4.49,
    category: 'Fries',
    image: 'https://placehold.co/600x400.png',
    rating: 4.3,
  },
  {
    id: 38,
    name: 'Poutine',
    description: 'A Canadian classic! Fries topped with cheese curds and rich gravy.',
    price: 7.49,
    category: 'Fries',
    image: 'https://placehold.co/600x400.png',
    rating: 4.5,
  },
  {
    id: 39,
    name: 'Strawberry Milkshake',
    description: 'A sweet and creamy shake made with real strawberries and vanilla ice cream.',
    price: 4.99,
    category: 'Beverages',
    image: 'https://placehold.co/600x400.png',
    rating: 4.8,
  },
  {
    id: 40,
    name: 'Vanilla Milkshake',
    description: 'A classic, smooth, and creamy vanilla bean milkshake.',
    price: 4.99,
    category: 'Beverages',
    image: 'https://placehold.co/600x400.png',
    rating: 4.7,
  },
  {
    id: 41,
    name: 'Iced Tea',
    description: 'Freshly brewed black tea, served chilled over ice. Sweetened or unsweetened.',
    price: 2.29,
    category: 'Beverages',
    image: 'https://placehold.co/600x400.png',
    rating: 4.4,
  },
  {
    id: 42,
    name: 'Orange Soda',
    description: 'A bubbly and sweet orange-flavored soda.',
    price: 1.99,
    category: 'Beverages',
    image: 'https://placehold.co/600x400.png',
    rating: 4.3,
  },
  {
    id: 43,
    name: 'Root Beer Float',
    description: 'A classic treat with scoops of vanilla ice cream floating in root beer.',
    price: 3.99,
    category: 'Beverages',
    image: 'https://placehold.co/600x400.png',
    rating: 4.6,
  },
  {
    id: 44,
    name: 'Bottled Water',
    description: 'Pure, simple, and refreshing spring water.',
    price: 1.49,
    category: 'Beverages',
    image: 'https://placehold.co/600x400.png',
    rating: 4.9,
  },
  {
    id: 45,
    name: 'Solo Deal Combo',
    description: 'Your choice of any burger, a regular fries, and a regular soda.',
    price: 14.99,
    category: 'Combos',
    image: 'https://placehold.co/600x400.png',
    rating: 4.6,
  },
  {
    id: 46,
    name: 'Pizza Slice Combo',
    description: 'A giant slice of pepperoni or cheese pizza, a side salad, and a regular soda.',
    price: 9.99,
    category: 'Combos',
    image: 'https://placehold.co/600x400.png',
    rating: 4.5,
  },
  {
    id: 47,
    name: 'Chicken Strips Combo',
    description: 'Four crispy chicken strips, regular fries, and your choice of dipping sauce.',
    price: 10.99,
    category: 'Combos',
    image: 'https://placehold.co/600x400.png',
    rating: 4.4,
  },
  {
    id: 48,
    name: 'Snack Attack Combo',
    description: 'A sampler of our best sides: onion rings, curly fries, and mozzarella sticks.',
    price: 12.99,
    category: 'Combos',
    image: 'https://placehold.co/600x400.png',
    rating: 4.7,
  },
  {
    id: 49,
    name: 'Veggie Combo',
    description: 'A Vegan Black Bean Burger, a side of sweet potato fries, and fresh lemonade.',
    price: 17.99,
    category: 'Combos',
    image: 'https://placehold.co/600x400.png',
    rating: 4.6,
  },
  {
    id: 50,
    name: 'Dessert Combo',
    description: 'Finish your meal right with a chocolate milkshake and a slice of chocolate lava cake.',
    price: 8.99,
    category: 'Combos',
    image: 'https://placehold.co/600x400.png',
    rating: 4.8,
  },
];
